LIBVA_CEDRUS_DRIVER_VERSION = c8e187aed5ba
LIBVA_CEDRUS_DRIVER_SITE = $(BR2_EXTERNAL_CEDRUS_PATH)/../libva
LIBVA_CEDRUS_DRIVER_SITE_METHOD = local
LIBVA_CEDRUS_DRIVER_DEPENDENCIES = host-pkgconf libva xlib_libX11
LIBVA_CEDRUS_DRIVER_AUTORECONF = YES

$(eval $(autotools-package))
